title: Brut de Thé
description: >
  Collectif qui explore le monde.
author: pntbr
email: pntbr@scopyleft.fr
repository: pntbr/amagogne.git

encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end

defaults:
  - scope:
      path: ""
    values:
      layout: article

plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-titles-from-headings
