title: Brut de Thé
description: >
  Collectif qui explore le monde du thé de tradition Chinoise. Nous vous proposons des ressources pour apprendre, approfondir ou découvrir les types de thé : vert, blanc, jaune, wulong, rouge, noir et Pu'Er et les ustensiles : Théière, Gaiwan et autres.
author: pntbr
email: pntbr@scopyleft.fr
repository: brutdethe/site.git

encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end

defaults:
  - scope:
      path: ""
    values:
      layout: article

plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-titles-from-headings
